sonar.organization=jsaldana-idrobo-key
sonar.projectKey=jsaldana-idrobo_rifaria
sonar.projectName=rifaria
sonar.sourceEncoding=UTF-8
sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.astro/**,**/coverage/**,**/.vercel/**,**/*.d.ts
sonar.issue.ignore.multicriteria=entrypoint1,entrypoint2,entrypoint3
sonar.issue.ignore.multicriteria.entrypoint1.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.entrypoint1.resourceKey=apps/api/src/main.ts
sonar.issue.ignore.multicriteria.entrypoint2.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.entrypoint2.resourceKey=apps/api/src/scripts/seed.ts
sonar.issue.ignore.multicriteria.entrypoint3.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.entrypoint3.resourceKey=apps/worker/src/main.ts
