sonar.projectName=rifaria
sonar.sourceEncoding=UTF-8
sonar.sources=apps,packages
sonar.tests=apps,packages
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.astro/**,**/coverage/**,**/.vercel/**,**/*.d.ts
